<?php
/**
 * EventsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  EtkinlikIo\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Etkinlik.io V2 API
 *
 * API for integrating with event content aggregated and categorized from many sources and organizers. Use this documentation to build applications on top of Etkinlik.io event data.
 *
 * The version of the OpenAPI document: 2.0.5
 * Contact: bilgi@etkinlik.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EtkinlikIo\Api\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use EtkinlikIo\Api\ApiException;
use EtkinlikIo\Api\Configuration;
use EtkinlikIo\Api\FormDataProcessor;
use EtkinlikIo\Api\HeaderSelector;
use EtkinlikIo\Api\ObjectSerializer;

/**
 * EventsApi Class Doc Comment
 *
 * @category Class
 * @package  EtkinlikIo\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EventsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getEvent' => [
            'application/json',
        ],
        'listEvents' => [
            'application/json',
        ],
        'recordEventImpression' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getEvent
     *
     * Event detail
     *
     * @param  int $id Event ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEvent'] to see the possible values for this operation
     *
     * @throws \EtkinlikIo\Api\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \EtkinlikIo\Api\Model\Event|\EtkinlikIo\Api\Model\ApiDuplicateRecordError|\EtkinlikIo\Api\Model\ApiGeneralError|\EtkinlikIo\Api\Model\ApiAuthorizationError|\EtkinlikIo\Api\Model\ApiNotFoundError|\EtkinlikIo\Api\Model\ApiDeletedError
     */
    public function getEvent($id, string $contentType = self::contentTypes['getEvent'][0])
    {
        list($response) = $this->getEventWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation getEventWithHttpInfo
     *
     * Event detail
     *
     * @param  int $id Event ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEvent'] to see the possible values for this operation
     *
     * @throws \EtkinlikIo\Api\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \EtkinlikIo\Api\Model\Event|\EtkinlikIo\Api\Model\ApiDuplicateRecordError|\EtkinlikIo\Api\Model\ApiGeneralError|\EtkinlikIo\Api\Model\ApiAuthorizationError|\EtkinlikIo\Api\Model\ApiNotFoundError|\EtkinlikIo\Api\Model\ApiDeletedError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getEventWithHttpInfo($id, string $contentType = self::contentTypes['getEvent'][0])
    {
        $request = $this->getEventRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\EtkinlikIo\Api\Model\Event',
                        $request,
                        $response,
                    );
                case 301:
                    return $this->handleResponseWithDataType(
                        '\EtkinlikIo\Api\Model\ApiDuplicateRecordError',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\EtkinlikIo\Api\Model\ApiGeneralError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\EtkinlikIo\Api\Model\ApiAuthorizationError',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\EtkinlikIo\Api\Model\ApiNotFoundError',
                        $request,
                        $response,
                    );
                case 410:
                    return $this->handleResponseWithDataType(
                        '\EtkinlikIo\Api\Model\ApiDeletedError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\EtkinlikIo\Api\Model\Event',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EtkinlikIo\Api\Model\Event',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 301:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EtkinlikIo\Api\Model\ApiDuplicateRecordError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EtkinlikIo\Api\Model\ApiGeneralError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EtkinlikIo\Api\Model\ApiAuthorizationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EtkinlikIo\Api\Model\ApiNotFoundError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 410:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EtkinlikIo\Api\Model\ApiDeletedError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getEventAsync
     *
     * Event detail
     *
     * @param  int $id Event ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEvent'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getEventAsync($id, string $contentType = self::contentTypes['getEvent'][0])
    {
        return $this->getEventAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getEventAsyncWithHttpInfo
     *
     * Event detail
     *
     * @param  int $id Event ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEvent'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getEventAsyncWithHttpInfo($id, string $contentType = self::contentTypes['getEvent'][0])
    {
        $returnType = '\EtkinlikIo\Api\Model\Event';
        $request = $this->getEventRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getEvent'
     *
     * @param  int $id Event ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEvent'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getEventRequest($id, string $contentType = self::contentTypes['getEvent'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getEvent'
            );
        }


        $resourcePath = '/events/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Etkinlik-Token');
        if ($apiKey !== null) {
            $headers['X-Etkinlik-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listEvents
     *
     * List events
     *
     * @param  string|null $format_ids Filter events by format IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $category_ids Filter events by category IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $venue_ids Filter events by venue IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $city_ids Filter records by city IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $start_gte Filter events by start time (greater than or equal). Valid datetime, e.g. YYYY-MM-DD HH:mm:ss. (optional)
     * @param  string|null $end_lte Filter events by end time (less than or equal). Valid datetime, e.g. YYYY-MM-DD HH:mm:ss. (optional)
     * @param  string|null $sort_by Sort order (case-insensitive). &#x60;upcoming&#x60;: upcoming events by start time ascending (default). &#x60;recent&#x60;: most recently added approved events. (optional, default to 'upcoming')
     * @param  int|null $skip Offset for pagination. (optional, default to 0)
     * @param  int|null $take Maximum number of results to return. (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listEvents'] to see the possible values for this operation
     *
     * @throws \EtkinlikIo\Api\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \EtkinlikIo\Api\Model\PaginatedEvents|\EtkinlikIo\Api\Model\ApiGeneralError|\EtkinlikIo\Api\Model\ApiAuthorizationError
     */
    public function listEvents($format_ids = null, $category_ids = null, $venue_ids = null, $city_ids = null, $start_gte = null, $end_lte = null, $sort_by = 'upcoming', $skip = 0, $take = 50, string $contentType = self::contentTypes['listEvents'][0])
    {
        list($response) = $this->listEventsWithHttpInfo($format_ids, $category_ids, $venue_ids, $city_ids, $start_gte, $end_lte, $sort_by, $skip, $take, $contentType);
        return $response;
    }

    /**
     * Operation listEventsWithHttpInfo
     *
     * List events
     *
     * @param  string|null $format_ids Filter events by format IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $category_ids Filter events by category IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $venue_ids Filter events by venue IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $city_ids Filter records by city IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $start_gte Filter events by start time (greater than or equal). Valid datetime, e.g. YYYY-MM-DD HH:mm:ss. (optional)
     * @param  string|null $end_lte Filter events by end time (less than or equal). Valid datetime, e.g. YYYY-MM-DD HH:mm:ss. (optional)
     * @param  string|null $sort_by Sort order (case-insensitive). &#x60;upcoming&#x60;: upcoming events by start time ascending (default). &#x60;recent&#x60;: most recently added approved events. (optional, default to 'upcoming')
     * @param  int|null $skip Offset for pagination. (optional, default to 0)
     * @param  int|null $take Maximum number of results to return. (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listEvents'] to see the possible values for this operation
     *
     * @throws \EtkinlikIo\Api\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \EtkinlikIo\Api\Model\PaginatedEvents|\EtkinlikIo\Api\Model\ApiGeneralError|\EtkinlikIo\Api\Model\ApiAuthorizationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function listEventsWithHttpInfo($format_ids = null, $category_ids = null, $venue_ids = null, $city_ids = null, $start_gte = null, $end_lte = null, $sort_by = 'upcoming', $skip = 0, $take = 50, string $contentType = self::contentTypes['listEvents'][0])
    {
        $request = $this->listEventsRequest($format_ids, $category_ids, $venue_ids, $city_ids, $start_gte, $end_lte, $sort_by, $skip, $take, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\EtkinlikIo\Api\Model\PaginatedEvents',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\EtkinlikIo\Api\Model\ApiGeneralError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\EtkinlikIo\Api\Model\ApiAuthorizationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\EtkinlikIo\Api\Model\PaginatedEvents',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EtkinlikIo\Api\Model\PaginatedEvents',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EtkinlikIo\Api\Model\ApiGeneralError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EtkinlikIo\Api\Model\ApiAuthorizationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listEventsAsync
     *
     * List events
     *
     * @param  string|null $format_ids Filter events by format IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $category_ids Filter events by category IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $venue_ids Filter events by venue IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $city_ids Filter records by city IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $start_gte Filter events by start time (greater than or equal). Valid datetime, e.g. YYYY-MM-DD HH:mm:ss. (optional)
     * @param  string|null $end_lte Filter events by end time (less than or equal). Valid datetime, e.g. YYYY-MM-DD HH:mm:ss. (optional)
     * @param  string|null $sort_by Sort order (case-insensitive). &#x60;upcoming&#x60;: upcoming events by start time ascending (default). &#x60;recent&#x60;: most recently added approved events. (optional, default to 'upcoming')
     * @param  int|null $skip Offset for pagination. (optional, default to 0)
     * @param  int|null $take Maximum number of results to return. (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listEvents'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listEventsAsync($format_ids = null, $category_ids = null, $venue_ids = null, $city_ids = null, $start_gte = null, $end_lte = null, $sort_by = 'upcoming', $skip = 0, $take = 50, string $contentType = self::contentTypes['listEvents'][0])
    {
        return $this->listEventsAsyncWithHttpInfo($format_ids, $category_ids, $venue_ids, $city_ids, $start_gte, $end_lte, $sort_by, $skip, $take, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listEventsAsyncWithHttpInfo
     *
     * List events
     *
     * @param  string|null $format_ids Filter events by format IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $category_ids Filter events by category IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $venue_ids Filter events by venue IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $city_ids Filter records by city IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $start_gte Filter events by start time (greater than or equal). Valid datetime, e.g. YYYY-MM-DD HH:mm:ss. (optional)
     * @param  string|null $end_lte Filter events by end time (less than or equal). Valid datetime, e.g. YYYY-MM-DD HH:mm:ss. (optional)
     * @param  string|null $sort_by Sort order (case-insensitive). &#x60;upcoming&#x60;: upcoming events by start time ascending (default). &#x60;recent&#x60;: most recently added approved events. (optional, default to 'upcoming')
     * @param  int|null $skip Offset for pagination. (optional, default to 0)
     * @param  int|null $take Maximum number of results to return. (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listEvents'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listEventsAsyncWithHttpInfo($format_ids = null, $category_ids = null, $venue_ids = null, $city_ids = null, $start_gte = null, $end_lte = null, $sort_by = 'upcoming', $skip = 0, $take = 50, string $contentType = self::contentTypes['listEvents'][0])
    {
        $returnType = '\EtkinlikIo\Api\Model\PaginatedEvents';
        $request = $this->listEventsRequest($format_ids, $category_ids, $venue_ids, $city_ids, $start_gte, $end_lte, $sort_by, $skip, $take, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listEvents'
     *
     * @param  string|null $format_ids Filter events by format IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $category_ids Filter events by category IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $venue_ids Filter events by venue IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $city_ids Filter records by city IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $start_gte Filter events by start time (greater than or equal). Valid datetime, e.g. YYYY-MM-DD HH:mm:ss. (optional)
     * @param  string|null $end_lte Filter events by end time (less than or equal). Valid datetime, e.g. YYYY-MM-DD HH:mm:ss. (optional)
     * @param  string|null $sort_by Sort order (case-insensitive). &#x60;upcoming&#x60;: upcoming events by start time ascending (default). &#x60;recent&#x60;: most recently added approved events. (optional, default to 'upcoming')
     * @param  int|null $skip Offset for pagination. (optional, default to 0)
     * @param  int|null $take Maximum number of results to return. (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listEvents'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listEventsRequest($format_ids = null, $category_ids = null, $venue_ids = null, $city_ids = null, $start_gte = null, $end_lte = null, $sort_by = 'upcoming', $skip = 0, $take = 50, string $contentType = self::contentTypes['listEvents'][0])
    {








        if ($skip !== null && $skip < 0) {
            throw new \InvalidArgumentException('invalid value for "$skip" when calling EventsApi.listEvents, must be bigger than or equal to 0.');
        }
        
        if ($take !== null && $take > 100) {
            throw new \InvalidArgumentException('invalid value for "$take" when calling EventsApi.listEvents, must be smaller than or equal to 100.');
        }
        if ($take !== null && $take < 1) {
            throw new \InvalidArgumentException('invalid value for "$take" when calling EventsApi.listEvents, must be bigger than or equal to 1.');
        }
        

        $resourcePath = '/events';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $format_ids,
            'format_ids', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $category_ids,
            'category_ids', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $venue_ids,
            'venue_ids', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $city_ids,
            'city_ids', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $start_gte,
            'start_gte', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $end_lte,
            'end_lte', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort_by,
            'sort_by', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $skip,
            'skip', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $take,
            'take', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Etkinlik-Token');
        if ($apiKey !== null) {
            $headers['X-Etkinlik-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation recordEventImpression
     *
     * Record event impression
     *
     * @param  int $id Event ID. (required)
     * @param  \EtkinlikIo\Api\Model\EventImpressionRequest|null $event_impression_request event_impression_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['recordEventImpression'] to see the possible values for this operation
     *
     * @throws \EtkinlikIo\Api\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \EtkinlikIo\Api\Model\EventImpressionCreated|\EtkinlikIo\Api\Model\ApiGeneralError|\EtkinlikIo\Api\Model\ApiAuthorizationError|\EtkinlikIo\Api\Model\ApiNotFoundError
     */
    public function recordEventImpression($id, $event_impression_request = null, string $contentType = self::contentTypes['recordEventImpression'][0])
    {
        list($response) = $this->recordEventImpressionWithHttpInfo($id, $event_impression_request, $contentType);
        return $response;
    }

    /**
     * Operation recordEventImpressionWithHttpInfo
     *
     * Record event impression
     *
     * @param  int $id Event ID. (required)
     * @param  \EtkinlikIo\Api\Model\EventImpressionRequest|null $event_impression_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['recordEventImpression'] to see the possible values for this operation
     *
     * @throws \EtkinlikIo\Api\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \EtkinlikIo\Api\Model\EventImpressionCreated|\EtkinlikIo\Api\Model\ApiGeneralError|\EtkinlikIo\Api\Model\ApiAuthorizationError|\EtkinlikIo\Api\Model\ApiNotFoundError, HTTP status code, HTTP response headers (array of strings)
     */
    public function recordEventImpressionWithHttpInfo($id, $event_impression_request = null, string $contentType = self::contentTypes['recordEventImpression'][0])
    {
        $request = $this->recordEventImpressionRequest($id, $event_impression_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\EtkinlikIo\Api\Model\EventImpressionCreated',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\EtkinlikIo\Api\Model\ApiGeneralError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\EtkinlikIo\Api\Model\ApiAuthorizationError',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\EtkinlikIo\Api\Model\ApiNotFoundError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\EtkinlikIo\Api\Model\EventImpressionCreated',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EtkinlikIo\Api\Model\EventImpressionCreated',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EtkinlikIo\Api\Model\ApiGeneralError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EtkinlikIo\Api\Model\ApiAuthorizationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EtkinlikIo\Api\Model\ApiNotFoundError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation recordEventImpressionAsync
     *
     * Record event impression
     *
     * @param  int $id Event ID. (required)
     * @param  \EtkinlikIo\Api\Model\EventImpressionRequest|null $event_impression_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['recordEventImpression'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function recordEventImpressionAsync($id, $event_impression_request = null, string $contentType = self::contentTypes['recordEventImpression'][0])
    {
        return $this->recordEventImpressionAsyncWithHttpInfo($id, $event_impression_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation recordEventImpressionAsyncWithHttpInfo
     *
     * Record event impression
     *
     * @param  int $id Event ID. (required)
     * @param  \EtkinlikIo\Api\Model\EventImpressionRequest|null $event_impression_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['recordEventImpression'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function recordEventImpressionAsyncWithHttpInfo($id, $event_impression_request = null, string $contentType = self::contentTypes['recordEventImpression'][0])
    {
        $returnType = '\EtkinlikIo\Api\Model\EventImpressionCreated';
        $request = $this->recordEventImpressionRequest($id, $event_impression_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'recordEventImpression'
     *
     * @param  int $id Event ID. (required)
     * @param  \EtkinlikIo\Api\Model\EventImpressionRequest|null $event_impression_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['recordEventImpression'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function recordEventImpressionRequest($id, $event_impression_request = null, string $contentType = self::contentTypes['recordEventImpression'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling recordEventImpression'
            );
        }



        $resourcePath = '/events/{id}/impressions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($event_impression_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($event_impression_request));
            } else {
                $httpBody = $event_impression_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Etkinlik-Token');
        if ($apiKey !== null) {
            $headers['X-Etkinlik-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
