<?php
/**
 * VenuesApi
 * PHP version 8.1
 *
 * @category Class
 * @package  EtkinlikIo\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Etkinlik.io V2 API
 *
 * API for integrating with event content aggregated and categorized from many sources and organizers. Use this documentation to build applications on top of Etkinlik.io event data.
 *
 * The version of the OpenAPI document: 2.0.9
 * Contact: bilgi@etkinlik.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EtkinlikIo\Api\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use EtkinlikIo\Api\ApiException;
use EtkinlikIo\Api\Configuration;
use EtkinlikIo\Api\FormDataProcessor;
use EtkinlikIo\Api\HeaderSelector;
use EtkinlikIo\Api\ObjectSerializer;

/**
 * VenuesApi Class Doc Comment
 *
 * @category Class
 * @package  EtkinlikIo\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class VenuesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getVenue' => [
            'application/json',
        ],
        'listVenues' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getVenue
     *
     * Venue detail
     *
     * @param  int $id Venue ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getVenue'] to see the possible values for this operation
     *
     * @throws \EtkinlikIo\Api\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \EtkinlikIo\Api\Model\Venue|\EtkinlikIo\Api\Model\ApiGeneralError|\EtkinlikIo\Api\Model\ApiAuthorizationError|\EtkinlikIo\Api\Model\ApiNotFoundError
     */
    public function getVenue($id, string $contentType = self::contentTypes['getVenue'][0])
    {
        list($response) = $this->getVenueWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation getVenueWithHttpInfo
     *
     * Venue detail
     *
     * @param  int $id Venue ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getVenue'] to see the possible values for this operation
     *
     * @throws \EtkinlikIo\Api\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \EtkinlikIo\Api\Model\Venue|\EtkinlikIo\Api\Model\ApiGeneralError|\EtkinlikIo\Api\Model\ApiAuthorizationError|\EtkinlikIo\Api\Model\ApiNotFoundError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getVenueWithHttpInfo($id, string $contentType = self::contentTypes['getVenue'][0])
    {
        $request = $this->getVenueRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\EtkinlikIo\Api\Model\Venue',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\EtkinlikIo\Api\Model\ApiGeneralError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\EtkinlikIo\Api\Model\ApiAuthorizationError',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\EtkinlikIo\Api\Model\ApiNotFoundError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\EtkinlikIo\Api\Model\Venue',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EtkinlikIo\Api\Model\Venue',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EtkinlikIo\Api\Model\ApiGeneralError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EtkinlikIo\Api\Model\ApiAuthorizationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EtkinlikIo\Api\Model\ApiNotFoundError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getVenueAsync
     *
     * Venue detail
     *
     * @param  int $id Venue ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getVenue'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getVenueAsync($id, string $contentType = self::contentTypes['getVenue'][0])
    {
        return $this->getVenueAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getVenueAsyncWithHttpInfo
     *
     * Venue detail
     *
     * @param  int $id Venue ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getVenue'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getVenueAsyncWithHttpInfo($id, string $contentType = self::contentTypes['getVenue'][0])
    {
        $returnType = '\EtkinlikIo\Api\Model\Venue';
        $request = $this->getVenueRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getVenue'
     *
     * @param  int $id Venue ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getVenue'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getVenueRequest($id, string $contentType = self::contentTypes['getVenue'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getVenue'
            );
        }


        $resourcePath = '/venues/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Etkinlik-Token');
        if ($apiKey !== null) {
            $headers['X-Etkinlik-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listVenues
     *
     * List venues
     *
     * @param  string|null $city_ids Filter records by city IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $district_ids Filter records by district IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $neighborhood_ids Filter records by neighborhood IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $status_ids Use 1 for approved, 0 for pending. By default all statuses are returned. (optional)
     * @param  int|null $skip Offset for pagination. (optional, default to 0)
     * @param  int|null $take Maximum number of results to return. (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listVenues'] to see the possible values for this operation
     *
     * @throws \EtkinlikIo\Api\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \EtkinlikIo\Api\Model\PaginatedVenues|\EtkinlikIo\Api\Model\ApiAuthorizationError
     */
    public function listVenues($city_ids = null, $district_ids = null, $neighborhood_ids = null, $status_ids = null, $skip = 0, $take = 50, string $contentType = self::contentTypes['listVenues'][0])
    {
        list($response) = $this->listVenuesWithHttpInfo($city_ids, $district_ids, $neighborhood_ids, $status_ids, $skip, $take, $contentType);
        return $response;
    }

    /**
     * Operation listVenuesWithHttpInfo
     *
     * List venues
     *
     * @param  string|null $city_ids Filter records by city IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $district_ids Filter records by district IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $neighborhood_ids Filter records by neighborhood IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $status_ids Use 1 for approved, 0 for pending. By default all statuses are returned. (optional)
     * @param  int|null $skip Offset for pagination. (optional, default to 0)
     * @param  int|null $take Maximum number of results to return. (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listVenues'] to see the possible values for this operation
     *
     * @throws \EtkinlikIo\Api\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \EtkinlikIo\Api\Model\PaginatedVenues|\EtkinlikIo\Api\Model\ApiAuthorizationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function listVenuesWithHttpInfo($city_ids = null, $district_ids = null, $neighborhood_ids = null, $status_ids = null, $skip = 0, $take = 50, string $contentType = self::contentTypes['listVenues'][0])
    {
        $request = $this->listVenuesRequest($city_ids, $district_ids, $neighborhood_ids, $status_ids, $skip, $take, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\EtkinlikIo\Api\Model\PaginatedVenues',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\EtkinlikIo\Api\Model\ApiAuthorizationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\EtkinlikIo\Api\Model\PaginatedVenues',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EtkinlikIo\Api\Model\PaginatedVenues',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EtkinlikIo\Api\Model\ApiAuthorizationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listVenuesAsync
     *
     * List venues
     *
     * @param  string|null $city_ids Filter records by city IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $district_ids Filter records by district IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $neighborhood_ids Filter records by neighborhood IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $status_ids Use 1 for approved, 0 for pending. By default all statuses are returned. (optional)
     * @param  int|null $skip Offset for pagination. (optional, default to 0)
     * @param  int|null $take Maximum number of results to return. (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listVenues'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listVenuesAsync($city_ids = null, $district_ids = null, $neighborhood_ids = null, $status_ids = null, $skip = 0, $take = 50, string $contentType = self::contentTypes['listVenues'][0])
    {
        return $this->listVenuesAsyncWithHttpInfo($city_ids, $district_ids, $neighborhood_ids, $status_ids, $skip, $take, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listVenuesAsyncWithHttpInfo
     *
     * List venues
     *
     * @param  string|null $city_ids Filter records by city IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $district_ids Filter records by district IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $neighborhood_ids Filter records by neighborhood IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $status_ids Use 1 for approved, 0 for pending. By default all statuses are returned. (optional)
     * @param  int|null $skip Offset for pagination. (optional, default to 0)
     * @param  int|null $take Maximum number of results to return. (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listVenues'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listVenuesAsyncWithHttpInfo($city_ids = null, $district_ids = null, $neighborhood_ids = null, $status_ids = null, $skip = 0, $take = 50, string $contentType = self::contentTypes['listVenues'][0])
    {
        $returnType = '\EtkinlikIo\Api\Model\PaginatedVenues';
        $request = $this->listVenuesRequest($city_ids, $district_ids, $neighborhood_ids, $status_ids, $skip, $take, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listVenues'
     *
     * @param  string|null $city_ids Filter records by city IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $district_ids Filter records by district IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $neighborhood_ids Filter records by neighborhood IDs. Use comma-separated values for multiple IDs. (optional)
     * @param  string|null $status_ids Use 1 for approved, 0 for pending. By default all statuses are returned. (optional)
     * @param  int|null $skip Offset for pagination. (optional, default to 0)
     * @param  int|null $take Maximum number of results to return. (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listVenues'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listVenuesRequest($city_ids = null, $district_ids = null, $neighborhood_ids = null, $status_ids = null, $skip = 0, $take = 50, string $contentType = self::contentTypes['listVenues'][0])
    {





        if ($skip !== null && $skip < 0) {
            throw new \InvalidArgumentException('invalid value for "$skip" when calling VenuesApi.listVenues, must be bigger than or equal to 0.');
        }
        
        if ($take !== null && $take > 100) {
            throw new \InvalidArgumentException('invalid value for "$take" when calling VenuesApi.listVenues, must be smaller than or equal to 100.');
        }
        if ($take !== null && $take < 1) {
            throw new \InvalidArgumentException('invalid value for "$take" when calling VenuesApi.listVenues, must be bigger than or equal to 1.');
        }
        

        $resourcePath = '/venues';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $city_ids,
            'city_ids', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $district_ids,
            'district_ids', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $neighborhood_ids,
            'neighborhood_ids', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $status_ids,
            'status_ids', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $skip,
            'skip', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $take,
            'take', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Etkinlik-Token');
        if ($apiKey !== null) {
            $headers['X-Etkinlik-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
