<?php
/**
 * Event
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  EtkinlikIo\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Etkinlik.io V2 API
 *
 * API for integrating with event content aggregated and categorized from many sources and organizers. Use this documentation to build applications on top of Etkinlik.io event data.
 *
 * The version of the OpenAPI document: 2.0.10
 * Contact: bilgi@etkinlik.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EtkinlikIo\Api\Model;

use \ArrayAccess;
use \EtkinlikIo\Api\ObjectSerializer;

/**
 * Event Class Doc Comment
 *
 * @category Class
 * @package  EtkinlikIo\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Event implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'Event';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'id' => 'int',
        'name' => 'string',
        'slug' => 'string',
        'url' => 'string',
        'content' => 'string',
        'start' => '\DateTime',
        'start_r001' => '\DateTime',
        'end' => '\DateTime',
        'end_r001' => '\DateTime',
        'timezone' => 'string',
        'is_free' => 'bool',
        'poster_url' => 'string',
        'ticket_url' => 'string',
        'phone' => 'string',
        'email' => 'string',
        'facebook_url' => 'string',
        'twitter_url' => 'string',
        'hashtag' => 'string',
        'web_url' => 'string',
        'live_url' => 'string',
        'android_url' => 'string',
        'ios_url' => 'string',
        'format' => '\EtkinlikIo\Api\Model\Format',
        'category' => '\EtkinlikIo\Api\Model\Category',
        'venue' => '\EtkinlikIo\Api\Model\Venue',
        'venue_type' => 'string',
        'venue_data' => '\EtkinlikIo\Api\Model\EventVenueData',
        'tags' => '\EtkinlikIo\Api\Model\Tag[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'id' => 'int32',
        'name' => null,
        'slug' => null,
        'url' => null,
        'content' => null,
        'start' => 'date-time',
        'start_r001' => 'date-time',
        'end' => 'date-time',
        'end_r001' => 'date-time',
        'timezone' => null,
        'is_free' => null,
        'poster_url' => null,
        'ticket_url' => null,
        'phone' => null,
        'email' => null,
        'facebook_url' => null,
        'twitter_url' => null,
        'hashtag' => null,
        'web_url' => null,
        'live_url' => null,
        'android_url' => null,
        'ios_url' => null,
        'format' => null,
        'category' => null,
        'venue' => null,
        'venue_type' => null,
        'venue_data' => null,
        'tags' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'id' => false,
        'name' => false,
        'slug' => false,
        'url' => false,
        'content' => false,
        'start' => false,
        'start_r001' => false,
        'end' => false,
        'end_r001' => true,
        'timezone' => false,
        'is_free' => false,
        'poster_url' => false,
        'ticket_url' => false,
        'phone' => true,
        'email' => true,
        'facebook_url' => true,
        'twitter_url' => true,
        'hashtag' => true,
        'web_url' => true,
        'live_url' => true,
        'android_url' => true,
        'ios_url' => true,
        'format' => false,
        'category' => false,
        'venue' => true,
        'venue_type' => false,
        'venue_data' => true,
        'tags' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'slug' => 'slug',
        'url' => 'url',
        'content' => 'content',
        'start' => 'start',
        'start_r001' => 'start_r001',
        'end' => 'end',
        'end_r001' => 'end_r001',
        'timezone' => 'timezone',
        'is_free' => 'is_free',
        'poster_url' => 'poster_url',
        'ticket_url' => 'ticket_url',
        'phone' => 'phone',
        'email' => 'email',
        'facebook_url' => 'facebook_url',
        'twitter_url' => 'twitter_url',
        'hashtag' => 'hashtag',
        'web_url' => 'web_url',
        'live_url' => 'live_url',
        'android_url' => 'android_url',
        'ios_url' => 'ios_url',
        'format' => 'format',
        'category' => 'category',
        'venue' => 'venue',
        'venue_type' => 'venue_type',
        'venue_data' => 'venue_data',
        'tags' => 'tags'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'slug' => 'setSlug',
        'url' => 'setUrl',
        'content' => 'setContent',
        'start' => 'setStart',
        'start_r001' => 'setStartR001',
        'end' => 'setEnd',
        'end_r001' => 'setEndR001',
        'timezone' => 'setTimezone',
        'is_free' => 'setIsFree',
        'poster_url' => 'setPosterUrl',
        'ticket_url' => 'setTicketUrl',
        'phone' => 'setPhone',
        'email' => 'setEmail',
        'facebook_url' => 'setFacebookUrl',
        'twitter_url' => 'setTwitterUrl',
        'hashtag' => 'setHashtag',
        'web_url' => 'setWebUrl',
        'live_url' => 'setLiveUrl',
        'android_url' => 'setAndroidUrl',
        'ios_url' => 'setIosUrl',
        'format' => 'setFormat',
        'category' => 'setCategory',
        'venue' => 'setVenue',
        'venue_type' => 'setVenueType',
        'venue_data' => 'setVenueData',
        'tags' => 'setTags'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'slug' => 'getSlug',
        'url' => 'getUrl',
        'content' => 'getContent',
        'start' => 'getStart',
        'start_r001' => 'getStartR001',
        'end' => 'getEnd',
        'end_r001' => 'getEndR001',
        'timezone' => 'getTimezone',
        'is_free' => 'getIsFree',
        'poster_url' => 'getPosterUrl',
        'ticket_url' => 'getTicketUrl',
        'phone' => 'getPhone',
        'email' => 'getEmail',
        'facebook_url' => 'getFacebookUrl',
        'twitter_url' => 'getTwitterUrl',
        'hashtag' => 'getHashtag',
        'web_url' => 'getWebUrl',
        'live_url' => 'getLiveUrl',
        'android_url' => 'getAndroidUrl',
        'ios_url' => 'getIosUrl',
        'format' => 'getFormat',
        'category' => 'getCategory',
        'venue' => 'getVenue',
        'venue_type' => 'getVenueType',
        'venue_data' => 'getVenueData',
        'tags' => 'getTags'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const VENUE_TYPE_VENUE = 'VENUE';
    public const VENUE_TYPE_ONLINE = 'ONLINE';
    public const VENUE_TYPE_MANUAL = 'MANUAL';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getVenueTypeAllowableValues()
    {
        return [
            self::VENUE_TYPE_VENUE,
            self::VENUE_TYPE_ONLINE,
            self::VENUE_TYPE_MANUAL,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('slug', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('content', $data ?? [], null);
        $this->setIfExists('start', $data ?? [], null);
        $this->setIfExists('start_r001', $data ?? [], null);
        $this->setIfExists('end', $data ?? [], null);
        $this->setIfExists('end_r001', $data ?? [], null);
        $this->setIfExists('timezone', $data ?? [], null);
        $this->setIfExists('is_free', $data ?? [], null);
        $this->setIfExists('poster_url', $data ?? [], null);
        $this->setIfExists('ticket_url', $data ?? [], null);
        $this->setIfExists('phone', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('facebook_url', $data ?? [], null);
        $this->setIfExists('twitter_url', $data ?? [], null);
        $this->setIfExists('hashtag', $data ?? [], null);
        $this->setIfExists('web_url', $data ?? [], null);
        $this->setIfExists('live_url', $data ?? [], null);
        $this->setIfExists('android_url', $data ?? [], null);
        $this->setIfExists('ios_url', $data ?? [], null);
        $this->setIfExists('format', $data ?? [], null);
        $this->setIfExists('category', $data ?? [], null);
        $this->setIfExists('venue', $data ?? [], null);
        $this->setIfExists('venue_type', $data ?? [], null);
        $this->setIfExists('venue_data', $data ?? [], null);
        $this->setIfExists('tags', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['slug'] === null) {
            $invalidProperties[] = "'slug' can't be null";
        }
        if ($this->container['url'] === null) {
            $invalidProperties[] = "'url' can't be null";
        }
        if ($this->container['content'] === null) {
            $invalidProperties[] = "'content' can't be null";
        }
        if ($this->container['start'] === null) {
            $invalidProperties[] = "'start' can't be null";
        }
        if ($this->container['start_r001'] === null) {
            $invalidProperties[] = "'start_r001' can't be null";
        }
        if ($this->container['end'] === null) {
            $invalidProperties[] = "'end' can't be null";
        }
        if ($this->container['timezone'] === null) {
            $invalidProperties[] = "'timezone' can't be null";
        }
        if ($this->container['is_free'] === null) {
            $invalidProperties[] = "'is_free' can't be null";
        }
        if ($this->container['poster_url'] === null) {
            $invalidProperties[] = "'poster_url' can't be null";
        }
        if ($this->container['ticket_url'] === null) {
            $invalidProperties[] = "'ticket_url' can't be null";
        }
        if ($this->container['format'] === null) {
            $invalidProperties[] = "'format' can't be null";
        }
        if ($this->container['category'] === null) {
            $invalidProperties[] = "'category' can't be null";
        }
        if ($this->container['venue_type'] === null) {
            $invalidProperties[] = "'venue_type' can't be null";
        }
        $allowedValues = $this->getVenueTypeAllowableValues();
        if (!is_null($this->container['venue_type']) && !in_array($this->container['venue_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'venue_type', must be one of '%s'",
                $this->container['venue_type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['tags'] === null) {
            $invalidProperties[] = "'tags' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id Event ID.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Event name.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets slug
     *
     * @return string
     */
    public function getSlug()
    {
        return $this->container['slug'];
    }

    /**
     * Sets slug
     *
     * @param string $slug Event slug.
     *
     * @return self
     */
    public function setSlug($slug)
    {
        if (is_null($slug)) {
            throw new \InvalidArgumentException('non-nullable slug cannot be null');
        }
        $this->container['slug'] = $slug;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url Event URL on Etkinlik.io.
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            throw new \InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets content
     *
     * @return string
     */
    public function getContent()
    {
        return $this->container['content'];
    }

    /**
     * Sets content
     *
     * @param string $content Event HTML content with detailed information.
     *
     * @return self
     */
    public function setContent($content)
    {
        if (is_null($content)) {
            throw new \InvalidArgumentException('non-nullable content cannot be null');
        }
        $this->container['content'] = $content;

        return $this;
    }

    /**
     * Gets start
     *
     * @return \DateTime
     * @deprecated
     */
    public function getStart()
    {
        return $this->container['start'];
    }

    /**
     * Sets start
     *
     * @param \DateTime $start **Deprecated.** Legacy event start in ISO8601 with offset for the event's `timezone` (wall-clock presentation). Still returned for backward compatibility. New integrations must use `start_r001` with `timezone`.
     *
     * @return self
     * @deprecated
     */
    public function setStart($start)
    {
        if (is_null($start)) {
            throw new \InvalidArgumentException('non-nullable start cannot be null');
        }
        $this->container['start'] = $start;

        return $this;
    }

    /**
     * Gets start_r001
     *
     * @return \DateTime
     */
    public function getStartR001()
    {
        return $this->container['start_r001'];
    }

    /**
     * Sets start_r001
     *
     * @param \DateTime $start_r001 Event start instant in UTC (ISO8601). Prefer with `end_r001` and `timezone` for new integrations.
     *
     * @return self
     */
    public function setStartR001($start_r001)
    {
        if (is_null($start_r001)) {
            throw new \InvalidArgumentException('non-nullable start_r001 cannot be null');
        }
        $this->container['start_r001'] = $start_r001;

        return $this;
    }

    /**
     * Gets end
     *
     * @return \DateTime
     * @deprecated
     */
    public function getEnd()
    {
        return $this->container['end'];
    }

    /**
     * Sets end
     *
     * @param \DateTime $end **Deprecated.** Legacy event end in ISO8601 with offset for the event's `timezone`. Still returned for backward compatibility. When the event has no scheduled end (`end_r001` is null), this value is local `start` plus 2 hours. New integrations must use `end_r001` with `timezone`.
     *
     * @return self
     * @deprecated
     */
    public function setEnd($end)
    {
        if (is_null($end)) {
            throw new \InvalidArgumentException('non-nullable end cannot be null');
        }
        $this->container['end'] = $end;

        return $this;
    }

    /**
     * Gets end_r001
     *
     * @return \DateTime|null
     */
    public function getEndR001()
    {
        return $this->container['end_r001'];
    }

    /**
     * Sets end_r001
     *
     * @param \DateTime|null $end_r001 Actual scheduled end instant in UTC (ISO8601) when available; null when the event has no end time. Prefer with `start_r001` for new integrations.
     *
     * @return self
     */
    public function setEndR001($end_r001)
    {
        if (is_null($end_r001)) {
            array_push($this->openAPINullablesSetToNull, 'end_r001');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('end_r001', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['end_r001'] = $end_r001;

        return $this;
    }

    /**
     * Gets timezone
     *
     * @return string
     */
    public function getTimezone()
    {
        return $this->container['timezone'];
    }

    /**
     * Sets timezone
     *
     * @param string $timezone IANA timezone identifier for the event (e.g. `Europe/Istanbul`). Always present and valid. Use with `start_r001` / `end_r001` for display in local wall-clock time.
     *
     * @return self
     */
    public function setTimezone($timezone)
    {
        if (is_null($timezone)) {
            throw new \InvalidArgumentException('non-nullable timezone cannot be null');
        }
        $this->container['timezone'] = $timezone;

        return $this;
    }

    /**
     * Gets is_free
     *
     * @return bool
     */
    public function getIsFree()
    {
        return $this->container['is_free'];
    }

    /**
     * Sets is_free
     *
     * @param bool $is_free `true` if the event is free, otherwise `false`.
     *
     * @return self
     */
    public function setIsFree($is_free)
    {
        if (is_null($is_free)) {
            throw new \InvalidArgumentException('non-nullable is_free cannot be null');
        }
        $this->container['is_free'] = $is_free;

        return $this;
    }

    /**
     * Gets poster_url
     *
     * @return string
     */
    public function getPosterUrl()
    {
        return $this->container['poster_url'];
    }

    /**
     * Sets poster_url
     *
     * @param string $poster_url Event poster image URL.
     *
     * @return self
     */
    public function setPosterUrl($poster_url)
    {
        if (is_null($poster_url)) {
            throw new \InvalidArgumentException('non-nullable poster_url cannot be null');
        }
        $this->container['poster_url'] = $poster_url;

        return $this;
    }

    /**
     * Gets ticket_url
     *
     * @return string
     */
    public function getTicketUrl()
    {
        return $this->container['ticket_url'];
    }

    /**
     * Sets ticket_url
     *
     * @param string $ticket_url Ticket URL when available; otherwise redirects to the event page.
     *
     * @return self
     */
    public function setTicketUrl($ticket_url)
    {
        if (is_null($ticket_url)) {
            throw new \InvalidArgumentException('non-nullable ticket_url cannot be null');
        }
        $this->container['ticket_url'] = $ticket_url;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string|null
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string|null $phone Contact phone for the event; null when not set.
     *
     * @return self
     */
    public function setPhone($phone)
    {
        if (is_null($phone)) {
            array_push($this->openAPINullablesSetToNull, 'phone');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('phone', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email Contact email for the event; null when not set.
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            array_push($this->openAPINullablesSetToNull, 'email');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('email', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets facebook_url
     *
     * @return string|null
     */
    public function getFacebookUrl()
    {
        return $this->container['facebook_url'];
    }

    /**
     * Sets facebook_url
     *
     * @param string|null $facebook_url Facebook profile or page for the event; null when not set.
     *
     * @return self
     */
    public function setFacebookUrl($facebook_url)
    {
        if (is_null($facebook_url)) {
            array_push($this->openAPINullablesSetToNull, 'facebook_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('facebook_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['facebook_url'] = $facebook_url;

        return $this;
    }

    /**
     * Gets twitter_url
     *
     * @return string|null
     */
    public function getTwitterUrl()
    {
        return $this->container['twitter_url'];
    }

    /**
     * Sets twitter_url
     *
     * @param string|null $twitter_url Twitter handle or URL for the event; null when not set.
     *
     * @return self
     */
    public function setTwitterUrl($twitter_url)
    {
        if (is_null($twitter_url)) {
            array_push($this->openAPINullablesSetToNull, 'twitter_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('twitter_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['twitter_url'] = $twitter_url;

        return $this;
    }

    /**
     * Gets hashtag
     *
     * @return string|null
     */
    public function getHashtag()
    {
        return $this->container['hashtag'];
    }

    /**
     * Sets hashtag
     *
     * @param string|null $hashtag Hashtag for the event; null when not set.
     *
     * @return self
     */
    public function setHashtag($hashtag)
    {
        if (is_null($hashtag)) {
            array_push($this->openAPINullablesSetToNull, 'hashtag');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('hashtag', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['hashtag'] = $hashtag;

        return $this;
    }

    /**
     * Gets web_url
     *
     * @return string|null
     */
    public function getWebUrl()
    {
        return $this->container['web_url'];
    }

    /**
     * Sets web_url
     *
     * @param string|null $web_url Website URL for the event; null when not set.
     *
     * @return self
     */
    public function setWebUrl($web_url)
    {
        if (is_null($web_url)) {
            array_push($this->openAPINullablesSetToNull, 'web_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('web_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['web_url'] = $web_url;

        return $this;
    }

    /**
     * Gets live_url
     *
     * @return string|null
     */
    public function getLiveUrl()
    {
        return $this->container['live_url'];
    }

    /**
     * Sets live_url
     *
     * @param string|null $live_url Live stream URL for the event; null when not set.
     *
     * @return self
     */
    public function setLiveUrl($live_url)
    {
        if (is_null($live_url)) {
            array_push($this->openAPINullablesSetToNull, 'live_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('live_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['live_url'] = $live_url;

        return $this;
    }

    /**
     * Gets android_url
     *
     * @return string|null
     */
    public function getAndroidUrl()
    {
        return $this->container['android_url'];
    }

    /**
     * Sets android_url
     *
     * @param string|null $android_url Android app URL for the event; null when not set.
     *
     * @return self
     */
    public function setAndroidUrl($android_url)
    {
        if (is_null($android_url)) {
            array_push($this->openAPINullablesSetToNull, 'android_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('android_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['android_url'] = $android_url;

        return $this;
    }

    /**
     * Gets ios_url
     *
     * @return string|null
     */
    public function getIosUrl()
    {
        return $this->container['ios_url'];
    }

    /**
     * Sets ios_url
     *
     * @param string|null $ios_url iOS app URL for the event; null when not set.
     *
     * @return self
     */
    public function setIosUrl($ios_url)
    {
        if (is_null($ios_url)) {
            array_push($this->openAPINullablesSetToNull, 'ios_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ios_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ios_url'] = $ios_url;

        return $this;
    }

    /**
     * Gets format
     *
     * @return \EtkinlikIo\Api\Model\Format
     */
    public function getFormat()
    {
        return $this->container['format'];
    }

    /**
     * Sets format
     *
     * @param \EtkinlikIo\Api\Model\Format $format format
     *
     * @return self
     */
    public function setFormat($format)
    {
        if (is_null($format)) {
            throw new \InvalidArgumentException('non-nullable format cannot be null');
        }
        $this->container['format'] = $format;

        return $this;
    }

    /**
     * Gets category
     *
     * @return \EtkinlikIo\Api\Model\Category
     */
    public function getCategory()
    {
        return $this->container['category'];
    }

    /**
     * Sets category
     *
     * @param \EtkinlikIo\Api\Model\Category $category category
     *
     * @return self
     */
    public function setCategory($category)
    {
        if (is_null($category)) {
            throw new \InvalidArgumentException('non-nullable category cannot be null');
        }
        $this->container['category'] = $category;

        return $this;
    }

    /**
     * Gets venue
     *
     * @return \EtkinlikIo\Api\Model\Venue|null
     * @deprecated
     */
    public function getVenue()
    {
        return $this->container['venue'];
    }

    /**
     * Sets venue
     *
     * @param \EtkinlikIo\Api\Model\Venue|null $venue **Deprecated.** Legacy venue object; present only when `venue_type` is `VENUE` (same registered venue as `venue_data`). Still returned for backward compatibility. New integrations must use `venue_type` and `venue_data`.
     *
     * @return self
     * @deprecated
     */
    public function setVenue($venue)
    {
        if (is_null($venue)) {
            array_push($this->openAPINullablesSetToNull, 'venue');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('venue', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['venue'] = $venue;

        return $this;
    }

    /**
     * Gets venue_type
     *
     * @return string
     */
    public function getVenueType()
    {
        return $this->container['venue_type'];
    }

    /**
     * Sets venue_type
     *
     * @param string $venue_type Venue type. - VENUE: Registered venue (`venue_data` is a Venue object) - ONLINE: Online event (`venue_data` is null) - MANUAL: Manually entered venue (`venue_data` is a VenueManual object)
     *
     * @return self
     */
    public function setVenueType($venue_type)
    {
        if (is_null($venue_type)) {
            throw new \InvalidArgumentException('non-nullable venue_type cannot be null');
        }
        $allowedValues = $this->getVenueTypeAllowableValues();
        if (!in_array($venue_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'venue_type', must be one of '%s'",
                    $venue_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['venue_type'] = $venue_type;

        return $this;
    }

    /**
     * Gets venue_data
     *
     * @return \EtkinlikIo\Api\Model\EventVenueData|null
     */
    public function getVenueData()
    {
        return $this->container['venue_data'];
    }

    /**
     * Sets venue_data
     *
     * @param \EtkinlikIo\Api\Model\EventVenueData|null $venue_data venue_data
     *
     * @return self
     */
    public function setVenueData($venue_data)
    {
        if (is_null($venue_data)) {
            array_push($this->openAPINullablesSetToNull, 'venue_data');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('venue_data', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['venue_data'] = $venue_data;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return \EtkinlikIo\Api\Model\Tag[]
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param \EtkinlikIo\Api\Model\Tag[] $tags Tags associated with the event.
     *
     * @return self
     */
    public function setTags($tags)
    {
        if (is_null($tags)) {
            throw new \InvalidArgumentException('non-nullable tags cannot be null');
        }
        $this->container['tags'] = $tags;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


