<?php
/**
 * EventVenueDataTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  EtkinlikIo\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Etkinlik.io V2 API
 *
 * API for integrating with event content aggregated and categorized from many sources and organizers. Use this documentation to build applications on top of Etkinlik.io event data.
 *
 * The version of the OpenAPI document: 2.0.7
 * Contact: bilgi@etkinlik.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace EtkinlikIo\Api\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * EventVenueDataTest Class Doc Comment
 *
 * @category    Class
 * @description Shape depends on &#x60;venue_type&#x60;. - VENUE: Venue object - ONLINE: null (no venue data) - MANUAL: VenueManual object
 * @package     EtkinlikIo\Api
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EventVenueDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "EventVenueData"
     */
    public function testEventVenueData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "slug"
     */
    public function testPropertySlug()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "about"
     */
    public function testPropertyAbout()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "lat"
     */
    public function testPropertyLat()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "lng"
     */
    public function testPropertyLng()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "web_url"
     */
    public function testPropertyWebUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "facebook_url"
     */
    public function testPropertyFacebookUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "twitter_url"
     */
    public function testPropertyTwitterUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "district"
     */
    public function testPropertyDistrict()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "neighborhood"
     */
    public function testPropertyNeighborhood()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "neighborhood_name"
     */
    public function testPropertyNeighborhoodName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "district_name"
     */
    public function testPropertyDistrictName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "city_name"
     */
    public function testPropertyCityName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
