<?php
/**
 * FormatsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  EtkinlikIo\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Etkinlik.io V2 API
 *
 * API for integrating with event content aggregated and categorized from many sources and organizers. Use this documentation to build applications on top of Etkinlik.io event data.
 *
 * The version of the OpenAPI document: 2.0.10
 * Contact: bilgi@etkinlik.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace EtkinlikIo\Api\Test\Api;

use \EtkinlikIo\Api\Configuration;
use \EtkinlikIo\Api\ApiException;
use \EtkinlikIo\Api\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FormatsApiTest Class Doc Comment
 *
 * @category Class
 * @package  EtkinlikIo\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FormatsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for listFormats
     *
     * List formats.
     *
     */
    public function testListFormats()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
